doctor/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('turn/', include('turn.urls', namespace='turn')),
    path('manager/', include('manager.urls', namespace='manager')),
    path('hesab/',include('hesab.urls',namespace='hesab')),
    ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

turn/urls.py
from django.urls import path
from .views import CreateAppointmentsView, DoctorDelayView, ReservedAppointmentsListView, PayView, VerifyView, \
    AllDaysAppointmentsView, DayAppointmentsView,UserToPatientView

app_name = 'turn'
urlpatterns = [
    # ...
    # path('create/', CreateAppointmentsView.as_view(), name='create_appointment'),
    # path('delay/', doctor_delay_view.as_view(), name='doctor_delay'),
    # path('reserved_list/',ReservedAppointments_listView.as_view(), name='reserved_list'),
    # path('pay/<int:appointment_id>/', pay_view.as_view(), name='pay'),
    # path('verify/', Verify_View.as_view(), name='verify'),
    # path('all_days/', AllDaysAppointmentsView.as_view(), name='all_days_appointments'),
    # path('all_days/<str:appointment_date>/', DayAppointmentsView.as_view(), name='day_appointments'),
    path('api/v1/create/', CreateAppointmentsView.as_view(), name='create_appointment_api'),
    path('api/v1/delay/', DoctorDelayView.as_view(), name='doctor_delay_api'),
    path('api/v1/reserved_list/', ReservedAppointmentsListView.as_view(), name='reserved_list_api'),
    path('api/v1/pay/<int:appointment_id>/', PayView.as_view(), name='pay_api'),
    path('api/v1/verify/', VerifyView.as_view(), name='verify_api'),
    path('api/v1/all_days/', AllDaysAppointmentsView.as_view(), name='all_days_appointments_api'),
    path('api/v1/all_days/<str:appointment_date>/', DayAppointmentsView.as_view(), name='day_appointments_api'),
    path('api/v1/getpatient/', UserToPatientView.as_view(), name='user_to_patient'),
]

turn/models.py
from django.db import models
from datetime import timedelta, datetime
from django.contrib.auth import get_user_model
from account.models import patent


# Create your models here.

class Doctor(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def create_appointments(self, start_date, end_date, start_time, end_time):
        current_date = start_date
        current_time = datetime.combine(datetime.min.date(), start_time)

        while current_date <= end_date:
            while current_time.time() < end_time:
                appointment_start = datetime.combine(current_date, current_time.time())
                appointment_end = appointment_start + timedelta(minutes=20)
                appointment = Appointment(doctor=self, start_date=current_date, end_date=current_date,
                                          start_time=appointment_start.time(), end_time=appointment_end.time())
                appointment.save()
                current_time += timedelta(minutes=20)

            current_date += timedelta(days=1)
            current_time = datetime.combine(datetime.min.date(), start_time)


class Appointment(models.Model):
    patent = models.ForeignKey(patent, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    is_reserved = models.BooleanField(default=False)
    payment = models.BooleanField(default=False)
    user_presence = models.BooleanField(default=False)

    def __str__(self):
        return f"Appointment with {self.doctor} from {self.start_date} {self.start_time} to {self.end_date} {self.end_time}"

turn/forms.py
from django import forms
from .models import Doctor,Appointment
class DoctorDelayForm(forms.Form):
    delay_time = forms.IntegerField(label='Delay Time')

turn/views.py
from django.shortcuts import render, redirect
from django.views import View
from rest_framework.response import Response
from .models import Doctor, Appointment
from datetime import datetime, timedelta, date
from rest_framework import status
from .forms import DoctorDelayForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.conf import settings
import requests
import json
from django.shortcuts import get_object_or_404
from account.models import patent
from rest_framework.views import APIView
from .serializers import AppointmentSerializer, DoctorSerializer
from rest_framework.permissions import IsAuthenticated


# permission_classes = [IsAuthenticated]
class CreateAppointmentsView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        doctors = Doctor.objects.all()
        serializer = DoctorSerializer(doctors, many=True)  # سریالیزه کردن کوئری‌ست
        return Response(serializer.data)

    def post(self, request):
        user_id = request.user
        print(user_id)
        request.data["user"] = user_id
        print(request.data)
        doctor_name = request.data.get('doctor')
        start_date = request.data.get('start_date')
        end_date = request.data.get('end_date')
        start_time = request.data.get('start_time')
        end_time = request.data.get('end_time')
        if start_date is None or end_date is None or start_time is None or end_time is None:
            return Response({'message': 'Missing required data'}, status=status.HTTP_400_BAD_REQUEST)

        try:
            doctor = Doctor.objects.get(name=doctor_name)
        except Doctor.DoesNotExist:
            return Response({'message': 'Doctor not found'}, status=status.HTTP_404_NOT_FOUND)

        try:
            start_date = datetime.strptime(start_date, '%Y-%m-%d').date()
            end_date = datetime.strptime(end_date, '%Y-%m-%d').date()
            start_time = datetime.strptime(start_time, '%H:%M').time()
            end_time = datetime.strptime(end_time, '%H:%M').time()
        except ValueError:
            return Response({'message': 'Invalid date or time format'}, status=status.HTTP_400_BAD_REQUEST)

        doctor.create_appointments(start_date, end_date, start_time, end_time)
        return Response({'message': 'Appointments created successfully'}, status=status.HTTP_201_CREATED)


class DoctorDelayView(View):
    def get(self, request):
        form = DoctorDelayForm()
        return render(request, 'doctor_delay.html', {'form': form})

    def post(self, request):
        form = DoctorDelayForm(request.POST)
        if form.is_valid():
            delay_time = form.cleaned_data['delay_time']
            appointments = Appointment.objects.filter(doctor=request.user)
            for appointment in appointments:
                appointment.start_time += timedelta(minutes=delay_time)
                appointment.end_time += timedelta(minutes=delay_time)
                appointment.save()
            return redirect('turn:reserved_appointments')
        return render(request, 'doctor_delay.html', {'form': form})


class ReservedAppointmentsListView(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        user = request.user
        appointments = Appointment.objects.filter(is_reserved=True)
        serializer = AppointmentSerializer(appointments, many=True)  # سریالیزه کردن کوئری‌ست
        return Response(serializer.data)


#######################################################################################################
# ? sandbox merchant
if settings.SANDBOX:
    sandbox = 'sandbox'
else:
    sandbox = 'www'

ZP_API_REQUEST = "https://sandbox.zarinpal.com/pg/rest/WebGate/PaymentRequest.json"
ZP_API_VERIFY = "https://sandbox.zarinpal.com/pg/rest/WebGate/PaymentVerification.json"
ZP_API_STARTPAY = "https://sandbox.zarinpal.com/pg/StartPay/"

amount = 95000  # Rial / Required
description = "توضیحات مربوط به تراکنش را در این قسمت وارد کنید"  # Required
phone = 'YOUR_PHONE_NUMBER'  # Optional

CallbackURL = 'http://127.0.0.1:8080/verify/'


class PayView(View):
    permission_classes = [IsAuthenticated]

    def get(self, request, appointment_id):
        appointment = Appointment.objects.get(id=appointment_id)
        data = {
            "MerchantID": settings.MERCHANT,
            "Amount": amount,
            "Description": description,
            "Phone": phone,
            "CallbackURL": CallbackURL,
        }
        data = json.dumps(data)
        req = requests.Request('POST', ZP_API_REQUEST, data=data, headers={'content-type': 'application/json'})
        prepared_req = req.prepare()
        try:
            response = requests.Session().send(prepared_req, timeout=10)
            if response.status_code == 200:
                response_data = response.json()
                if response_data['Status'] == 100:
                    appointment.user = request.user
                    appointment.is_reserved = True
                    appointment.save()
                    return redirect(ZP_API_STARTPAY + str(response_data['Authority']))
                else:
                    return render(request, 'error.html', {'message': 'Payment request failed'})
            return render(request, 'error.html', {'message': 'Unknown error occurred'})

        except requests.exceptions.Timeout:
            return render(request, 'error.html', {'message': 'Payment request timed out'})
        except requests.exceptions.ConnectionError:
            return render(request, 'error.html', {'message': 'Connection error occurred'})


class VerifyView(View):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        authority = request.GET.get('Authority')
        if authority:
            verification_result = self.verify(authority)
            if verification_result['status']:
                return render(request, 'success.html', {'ref_id': verification_result['RefID']})
            else:
                return render(request, 'error.html', {'message': 'Payment verification failed'})
        else:
            return render(request, 'error.html', {'message': 'Invalid payment request'})

    def verify(self, authority):

        data = {
            "MerchantID": settings.MERCHANT,
            "Authority": authority,
        }
        data = json.dumps(data)
        headers = {'content-type': 'application/json', 'content-length': str(len(data))}
        response = requests.post(ZP_API_VERIFY, data=data, headers=headers)
        if response.status_code == 200:
            response_data = response.json()
            if response_data['Status'] == 100:
                return {'status': True, 'RefID': response_data['RefID']}
            else:
                return {'status': False, 'code': str(response_data['Status'])}
        return {'status': False, 'code': 'Unknown error occurred'}


class AllDaysAppointmentsView(APIView):
    def get(self, request):
        today = date(2023, 6, 29)
        all_days = [today + timedelta(days=i) for i in range(30)]
        return Response({'all_days': all_days})


class DayAppointmentsView(APIView):
    def get(self, request, appointment_date):
        appointments = Appointment.objects.filter(start_date=appointment_date, is_reserved=False)
        serializer = AppointmentSerializer(appointments, many=True)
        return Response(serializer.data)

    permission_classes = [IsAuthenticated]

    def post(self, request, appointment_date):
        user = request.user
        appointment_id = request.data.get('appointment_id')

        try:
            appointment = Appointment.objects.get(id=appointment_id, is_reserved=False)
        except Appointment.DoesNotExist:
            return Response({'message': 'Appointment not found or already reserved'}, status=status.HTTP_404_NOT_FOUND)

        if appointment.is_reserved:
            return Response({'message': 'Appointment is already reserved'}, status=status.HTTP_400_BAD_REQUEST)

        user_patents = patent.objects.filter(user=user)

        if request.data.get('selected_patient'):
            selected_patent_id = request.data.get('selected_patient')
            #appointment.patent = get_object_or_404(patent, id=selected_patent_id, user=user)
        else:
            return Response({'message': 'You must select a patient'}, status=status.HTTP_400_BAD_REQUEST)

        payment_url = reverse('turn:pay_api', args=[appointment.id])

        return Response({
            'message': 'Appointment reserved successfully',
            'payment_url': payment_url,
        }, status=status.HTTP_200_OK)


class UserToPatientView(APIView):

    def get(self, requset):
        user = requset.user
        user_patents = patent.objects.filter(user=user)
        return Response({'user_patents': [patent.id for patent in user_patents]}, status=status.HTTP_200_OK)

turn/templates/all_days_appointments.html
<!DOCTYPE html>
<html>
<head>
    <title>All Appointments</title>
</head>
<body>
    <h2>All Days Appointments</h2>

  <ul>
    {% for day in all_days %}
      <li><a href="{% url 'turn:day_appointments' appointment_date=day %}">{{ day }}</a></li>
    {% endfor %}
  </ul>
</body>
</html>

turn/templates/appointment_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>سلام</title>
</head>
<body>

</body>
</html>

turn/templates/create_appointment.html
<h1>Create Appointment</h1>
<form method="POST" action="{% url 'turn:create_appointment' %}">
    {% csrf_token %}
  <label for="id_doctor">Doctor:</label>
  <select name="doctor" id="id_doctor">
    {% for doctor in doctors %}
      <option value="{{ doctor.id }}">{{ doctor.name }}</option>
    {% endfor %}
  </select>
  <br>
  <label for="id_start_date">Start Date:</label>
  <input type="date" name="start_date" id="id_start_date">
  <br>
  <label for="id_end_date">End Date:</label>
  <input type="date" name="end_date" id="id_end_date">
  <br>
  <label for="id_start_time">Start Time:</label>
  <input type="time" name="start_time" id="id_start_time">
  <br>
  <label for="id_end_time">End Time:</label>
  <input type="time" name="end_time" id="id_end_time">
  <br>
  <button type="submit">Create</button>
</form>

turn/templates/day_appointments.html
<h1>Choose an Available Appointment</h1>
<form method="POST" >
  {% csrf_token %}
  <ul>
    {% for appointment in appointments %}
      <li>
        {{ appointment.start_time }} - {{ appointment.end_time }}
        <input type="radio" name="appointment_id" value="{{ appointment.id }}">
        <label>{{ appointment }}</label>
          <label>{{ appointment.patent }}</label>
        <span>Doctor Delay: {{ appointment.doctor_delay|default:"Not Set" }}</span>
      <a href="{% url 'turn:pay' appointment_id=appointment.id %}">Pay for Appointment</a>
      </li>
    {% empty %}
      <li>No available appointments.</li>
    {% endfor %}
  </ul>
  <button type="submit">Reserve</button>
</form>

turn/templates/doctor_delay.html
<!-- doctor_delay.html -->
<h1>Doctor Delay</h1>
<form method="POST" action="{% url 'turn:doctor_delay' %}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit</button>
</form>

turn/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Error</title>
</head>
<body>
    <h1>Error</h1>
    <p>{{ message }}</p>
</body>
</html>

turn/templates/reserved_appoint_list.html
<h1>Reserved Appointments</h1>
<ul>
  {% for appointment in appointments %}
    <li>{{ appointment }}</li>
      <li>{{ appointment.user }}</li>

  {% empty %}
    <li>No reserved appointments.</li>
  {% endfor %}
</ul>

turn/templates/reserved_appointments.html
<h1>Choose an Available Appointment</h1>
<form method="POST" action="{% url 'turn:reserved_appointments' %}">
  {% csrf_token %}
  <ul>
    {% for appointment in appointments %}
      <li>
        <input type="radio" name="appointment_id" value="{{ appointment.id }}">
        <label>{{ appointment }}</label>
          <label>{{ appointment.patent }}</label>
        <span>Doctor Delay: {{ appointment.doctor_delay|default:"Not Set" }}</span>
      <a href="{% url 'turn:pay' appointment_id=appointment.id %}">Pay for Appointment</a>
      </li>
    {% empty %}
      <li>No available appointments.</li>
    {% endfor %}
  </ul>
  <button type="submit">Reserve</button>
</form>